### PR TITLE
test: Cli tests

### PR DESCRIPTION
**Pull request by yahu1031**
## Description
Added basic command line utils test cases.

### Issues to link
https://github.com/serverpod/serverpod/issues/4

## Pre-launch Checklist

- [x] I read the [Contribute](https://docs.serverpod.dev/contribute) page and followed the process outlined there for submitting PRs.
- [x] I read and followed the [Dart Style Guide](https://dart.dev/guides/language/effective-dart/style) and formatted the code with [dart format](https://dart.dev/tools/dart-format).
- [x] I listed at least one issue that this PR fixes in the description above.
- [x] I updated/added relevant documentation (doc comments with `///`), and made sure that the document follows the same style as other Serverpod documentation. I checked spelling and grammar.
- [x] I added new tests to check the change I am making.
- [x] All existing and new tests are passing.
- [x] Any breaking changes are documented below.

## Breaking changes

- Yes, breaking changes were being done like adding return types to some void functions like [`killAll()`](https://github.com/yahu1031/serverpod/blob/cli-tests/tools/serverpod_cli/bin/util/process_killer_extension.dart#L4)
- A very [platform specific test](https://github.com/yahu1031/serverpod/blob/cli-tests/tools/serverpod_cli/test/commandline_test.dart#L32).

### CODE REVIEW

**Comment by yahu1031** [comment]
uffff finally 😄

**Comment by yahu1031** [comment]
This is still under dev. Just need a quick view though.

**Comment by vlidholt** [comment]
I cannot approve this as it currently is implemented as it doesn't follow the specs outlined in the #4 issue.

- Tests are not places in under tests/cli_tests
- Tests doesn't actually run the tooling. It should run `serverpod create` and `serverpod generate` from the CLI.
- It should compare to a golden version of the generated files (this may strictly not be required for a start, it may be ok to just check a couple of files).
- Tests should be run both in CI and locally from `util/run_tests`.

**Comment by yahu1031** [comment]
Yes @vlidholt, I have mentioned why I didn't place that in tests/cli_tests https://github.com/serverpod/serverpod/issues/4#issuecomment-1233017817

**Comment by vlidholt** [comment]
The tests can be in tests/cli_tests if they are integration tests instead of unit tests. See the second point in my last comment.

**Comment by vlidholt** [comment]
These are now added. Closing this.

**Pull request closed without merging**
