### PR TITLE
Add short-circuit evaluation to `&` and `|` in queries

### PR DESCRIPTION
**Pull request by lukehutch**
This PR:
1. allows the user to use `bool` values directly in expressions (they get wrapped with `Constant(bool)`);
2. adds basic short-circuit evaluation, to simplify queries (presumably Postgres also does this, but why not)

(I didn't write any tests... sorry, I really don't have time to do so right now...)

## Pre-launch Checklist

- [x] I read the [Contribute](https://docs.serverpod.dev/contribute) page and followed the process outlined there for submitting PRs.
- [x] This update contains only one single feature or bug fix and nothing else. (If you are submitting multiple fixes, please make multiple PRs.)
- [x] I read and followed the [Dart Style Guide](https://dart.dev/guides/language/effective-dart/style) and formatted the code with [dart format](https://dart.dev/tools/dart-format).
- [x] I listed at least one issue that this PR fixes in the description above.
- [x] I updated/added relevant documentation (doc comments with `///`), and made sure that the documentation follows the same style as other Serverpod documentation. I checked spelling and grammar.
- [ ] I added new tests to check the change I am making.
- [x] All existing and new tests are passing.
- [x] Any breaking changes are documented below.

If you need help, consider asking for advice on the [discussion board](https://github.com/serverpod/serverpod/discussions).

### CODE REVIEW

**Comment by lukehutch** [comment]
The analyzer gives this error on GitHub (but not locally):

```
info - lib/src/database/expressions.dart:29:15 - 'Constant.new' is deprecated and shouldn't be used. Use Constant.bool or Constant.string instead. Try replacing the use of the deprecated member with the replacement. - deprecated_member_use_from_same_package
```

However, `Constant.bool` doesn't exist, at least in the branch I'm working from...

**Comment by SandPod** [comment]
Seems like a nice addition to add support for operations directly with bool values.
Can take a look at this one once we are done with relations.

**Comment by lukehutch** [comment]
It's useful when you what to insert some condition into the expression-builder syntax, inline, rather than creating two entire separate expressions for the two different queries you want to run, depending on the condition value.

**Comment by lukehutch** [comment]
Here's an example from my own code that shows the need for this:

```dart
    // Get all endorsements of requested user, by any other user.
    final endorsementsFuture = requestingOwnProfile
        ? Endorsement.find(session,
            where: (t) => t.otherUserId.equals(requestedUserId))
        // If not requesting own profile, require endorsements to be
        // approved before they can be viewed by another user
        : Endorsement.find(session,
            where: (t) => t.otherUserId.equals(requestedUserId) & t.approved);
```

Now this could be written as the following, but having to use `Constant` is unexpected, and the expression doesn't get simplified where possible before it's converted to SQL:

```dart
    // Get all endorsements of requested user, by any other user.
    final endorsementsFuture = Endorsement.find(session,
        where: (t) =>
            t.otherUserId.equals(requestedUserId) &
            (t.approved | Constant(requestingOwnProfile)));
```

Actually probably using `requestingOwnProfile` rather than `Constant(requestingOwnProfile)` still works, because a `bool` value will just get serialized to JSON in this situation, but still, the query is not simplified as it could be.

**Comment by lukehutch** [comment]
N.B. this change will mean that expressions erroneously using `==` instead of `.equals` could be wrongly and silently accepted as `bool` values (somewhat related to #1302).

**Comment by lukehutch** [comment]
More complete example of how conditional queries need to be written currently, before this PR:

```dart
  Expression _checkBlocked(EndorsementTable t, int endorserUserId,
      int endorseeUserId, int viewerUserId) {
    // Check 2-way block between endorser and endorsee
    Expression endorsementCheck(LikeActionTable likeAction) =>
        ((likeAction.userId.equals(endorserUserId) &
                likeAction.otherUserId.equals(endorseeUserId)) |
            (likeAction.userId.equals(endorseeUserId) &
                likeAction.otherUserId.equals(endorserUserId)));
    return t.likeActions.none((likeAction) =>
        (viewerUserId == endorseeUserId || viewerUserId == endorseeUserId
            // 2-way check
            ? endorsementCheck(likeAction)
            // If viewer is a 3rd party, then need to check all 6 block
            // directions (3-way check)
            : endorsementCheck(likeAction) &
                ((likeAction.userId.equals(viewerUserId) &
                        likeAction.otherUserId.equals(endorseeUserId)) |
                    (likeAction.userId.equals(endorseeUserId) &
                        likeAction.otherUserId.equals(viewerUserId)) |
                    (likeAction.userId.equals(viewerUserId) &
                        likeAction.otherUserId.equals(endorserUserId)) |
                    (likeAction.userId.equals(endorserUserId) &
                        likeAction.otherUserId.equals(viewerUserId)))) &
        likeAction.likeActionType.equals(LikeActionType.block));
  }
```

**Pull request closed without merging**
