### PR TITLE
feat: Improve error handling in SignInWithGoogle by rethrowing exceptions

### LINKED ISSUE #2417: Improve error handling in SignInWithGoogle by rethrowing exceptions
**Is your feature request related to a problem? Please describe.**
When a user cancels the sign-in process, the current method simply returns `null`. However, an exception occurs indicating that the sign-in was aborted. It would be more useful to rethrow the exception, allowing us to differentiate between the types of exceptions that occur, including distinguishing between an actual error and a user cancellation.

**Describe the solution you'd like**
In the try-catch block, instead of returning `null`, `rethrow` the exception. 

**Additional context**
https://github.com/serverpod/serverpod/blob/03edf7f1ffcf7fa0c45cccc075193c5647b74dfa/modules/serverpod_auth/serverpod_auth_google_flutter/lib/src/auth.dart#L102-L106

### PR DESCRIPTION
**Pull request by Arnooodles**
This PR enhances the exception handling in the SignInWithGoogle process by rethrowing exceptions. This will allow us to differentiate between the types of exceptions that occur, including distinguishing between an actual error and a user cancellation.

closes #2417 

## Pre-launch Checklist

- [x] I read the [Contribute](https://docs.serverpod.dev/contribute) page and followed the process outlined there for submitting PRs.
- [x] This update contains only one single feature or bug fix and nothing else. (If you are submitting multiple fixes, please make multiple PRs.)
- [x] I read and followed the [Dart Style Guide](https://dart.dev/guides/language/effective-dart/style) and formatted the code with [dart format](https://dart.dev/tools/dart-format).
- [x] I listed at least one issue that this PR fixes in the description above.
- [ ] I updated/added relevant documentation (doc comments with `///`), and made sure that the documentation follows the same style as other Serverpod documentation. I checked spelling and grammar.
- [ ] I added new tests to check the change I am making.
- [ ] All existing and new tests are passing.
- [x] Any breaking changes are documented below.

### CODE REVIEW

**Comment by Arnooodles** [comment]
recheck

**Comment by Arnooodles** [comment]
I have read the CLA Document and I hereby sign the CLA

**Review by SandPod — CHANGES_REQUESTED** [review]
I understand your need for getting the specific exception that failed the google authentication.

But making this change is a breaking change for the interface that is not easy to find as a user.

Therefore I suggest that we introduce an optional parameter that is a callback named `onError(...)` that takes the error and stack trace that is called inside of the exception method. This would allow you to retrieve the error reason without breaking the interface and execution patch of the code.

**Review by SandPod — APPROVED** [review]
LGTM! 👍
Will merge this once main is green again.

**Pull request merged**
