### PR TITLE
Firebase login fixes

### PR DESCRIPTION
**Pull request by lukehutch**
* Adds a missing `Navigator.of(context).pop()` on exit (the dialog stays open after login success/failure). (Although I had to capture the navigator instance before pushing the route, because `context` is not available across an async gap.)
* Uses the return value of the route to return the `UserInfo?` (which is what it's designed for) rather than a `Completer`.
* If Firebase login fails due to exception, nothing is reported to the terminal. This prints the exception details.
* Also pops on `AuthCanceledAction`. This may also need to be added for `SignedOutAction` and/or `AccountDeletedAction`, I'm not sure. Please take a look at the Firebase docs to ensure that whatever action is taken, the route that is pushed is always popped at the end.

## Pre-launch Checklist

- [x] I read the [Contribute](https://docs.serverpod.dev/contribute) page and followed the process outlined there for submitting PRs.
- [x] This update contains only one single feature or bug fix and nothing else. (If you are submitting multiple fixes, please make multiple PRs.)
- [x] I read and followed the [Dart Style Guide](https://dart.dev/guides/language/effective-dart/style) and formatted the code with [dart format](https://dart.dev/tools/dart-format).
- [x] I listed at least one issue that this PR fixes in the description above.
- [x] I updated/added relevant documentation (doc comments with `///`), and made sure that the documentation follows the same style as other Serverpod documentation. I checked spelling and grammar.
- [ ] I added new tests to check the change I am making.
- [ ] All existing and new tests are passing.
- [ ] Any breaking changes are documented below.

### CODE REVIEW

**Review by Isakdl — APPROVED** [review]
LGTM, but need to run this code before we merge just to be sure 😄

**Comment by lukehutch** [comment]
Right -- see also my last bullet point though, this may still be incomplete.

**Comment by klkucaj** [comment]
Hi @lukehutch,
@SandPod asked me to make some small changes here. Is it okay with you if I proceed?

**Comment by lukehutch** [comment]
@klkucaj yes, please go ahead!

**Comment by SandPod** [comment]
These changes have been merge as part of this PR: https://github.com/serverpod/serverpod/pull/2334

**Pull request closed without merging**
