### PR TITLE
Added Cloud Run Support

### PR DESCRIPTION
**Pull request by ajay-k07**
Added Cloud Run Support by creating a separate Workflow and documented the steps which need to be followed along with screen shorts
 
https://github.com/serverpod/serverpod_docs/pull/4
 
_List which issues are fixed by this PR. You must list at least one issue._

Deployment Support to Cloud Run

## Pre-launch Checklist

- [x] I read the [Contribute](https://docs.serverpod.dev/contribute) page and followed the process outlined there for submitting PRs.
- [x] This update cointains only one single feature or bug fix and nothing else. (If you are submitting multiple fixes, please make multiple PRs.)
- [x] I read and followed the [Dart Style Guide](https://dart.dev/guides/language/effective-dart/style) and formatted the code with [dart format](https://dart.dev/tools/dart-format).
- [x] I listed at least one issue that this PR fixes in the description above.
- [x] I updated/added relevant documentation (doc comments with `///`), and made sure that the documentation follows the same style as other Serverpod documentation. I checked spelling and grammar.
- [ ] I added new tests to check the change I am making.
- [x] All existing and new tests are passing.
- [x] Any breaking changes are documented below.

### CODE REVIEW

**Comment by ajay-k07** [comment]
I have read the CLA Document and I hereby sign the CLA

**Comment by vlidholt** [comment]
For this to be approved, it need full support of all features in the AWS deployment.

1. Deployment of new versions through Github.
2. Support for autoscaling.
3. Separate instances for Postgres and Redis.
4. Support for file uploads.
5. Correct setup for certificates and domain names.

I think at the current state, this may be better off as a tutorial. I would be happy to link to it from the documentation.

**Review by vlidholt — CHANGES_REQUESTED** [review]
For this to be approved, it need full support of all features in the AWS deployment.

1. Deployment of new versions through Github.
2. Support for autoscaling.
3. Separate instances for Postgres and Redis.
4. Support for file uploads.
5. Correct setup for certificates and domain names.

I think at the current state, this may be better off as a tutorial. I would be happy to link to it from the documentation.

**Comment by ajay-k07** [comment]
Thanks for the suggestion.

As of now when we do a push to GitHub it will create a new revision of service and migrate the traffic to the new one. The old one will still exist if some problem occurs we can change the traffic from new revision to old revision. 

Cloud run automatically supports scalling we can even spin up 100 of serverpod service running within seconds.

We are packing our serverpod server into a docker( size ~30mb ) so that we can easily deploy them to any cloud services or even physical servers 


As Suggested I will work on that postgres , redis , domain and certification part. And will make it as a complete solution and will keep you posted. If possible can you create this as feature and assign to me

**Comment by vlidholt** [comment]
We will soon be starting work on GCP support, this may be a nice starting point!

**Comment by ajay-k07** [comment]
Hi @vlidholt  that's good to hear. Please let me know how can I help you 😃

**Comment by vlidholt** [comment]
Thank you! I started working on this now. Looks like a great entry point. :)

**Comment by vlidholt** [comment]
I've been working on GCP deployment over the past weeks. There is a GCP module up for review here:
https://github.com/serverpod/google_cloud_serverpod_gce/pull/1

I'll use this code as a base for the deployment, so @ajay-k07 will get credited as co-author.

**Comment by ps6067966** [comment]
I wanted to use serverpod for production apps, is it possible to deploy or should we wait for some for time?

**Comment by vlidholt** [comment]
We have added full support for Cloud Run or Compute Engine. The guides for deploying your Serverpod are available here:
https://docs.serverpod.dev/deployments/deployment-strategy

**Pull request closed without merging**
