### PR TITLE
feat: Add Support for UUIDs

### LINKED ISSUE #635: Add support for UUID
It would be nice to be able to use UUID types with the database.

### PR DESCRIPTION
**Pull request by fischerscode**
Adds support for UUIDs. They are represented as a `String` on the dart side, and as an [`uuid`](https://www.postgresql.org/docs/current/datatype-uuid.html) in the database.

Fix #635

I decided to introduce `_uuid` as a 'virtual' type.

This is an alternative implementation to #641.
Close #641

## Pre-launch Checklist

- [x] I read the [Contribute](https://docs.serverpod.dev/contribute) page and followed the process outlined there for submitting PRs.
- [x] This update contains only one single feature or bug fix and nothing else. (If you are submitting multiple fixes, please make multiple PRs.)
- [x] I read and followed the [Dart Style Guide](https://dart.dev/guides/language/effective-dart/style) and formatted the code with [dart format](https://dart.dev/tools/dart-format).
- [x] I listed at least one issue that this PR fixes in the description above.
- [x] I updated/added relevant documentation (doc comments with `///`), and made sure that the documentation follows the same style as other Serverpod documentation. I checked spelling and grammar.
- [x] I added new tests to check the change I am making.
- [x] All existing and new tests are passing.
- [x] Any breaking changes are documented below.

If you need help, consider asking for advice on the [discussion board](https://github.com/serverpod/serverpod/discussions).

## Breaking changes

*none*

*(In theory, someone could have used `_uuid` as a type before, but since the name starts with an underscore, this is more then unlikely)*

### CODE REVIEW

**Comment by vlidholt** [comment]
@fischerscode, perhaps it would be nicer to use the https://pub.dev/packages/uuid package to do this proper?

**Comment by fischerscode** [comment]
So, you would use [UuidValue](https://pub.dev/documentation/uuid/latest/uuid/UuidValue-class.html) instead of String?

The downside is that we would need an additional dependency.

**Comment by fischerscode** [comment]
> @fischerscode, perhaps it would be nicer to use the https://pub.dev/packages/uuid package to do this proper?

Implemented in #641 as an alternative to this PR.

**Comment by fischerscode** [comment]
This PR now includes c2672e5. I'm not sure, why the change occurred while regenerating...

**Comment by vlidholt** [comment]
I'm closing this one. The one with Uuid objects feels more correct to me.

**Pull request closed without merging**
