### PR TITLE
added Expression

### PR DESCRIPTION
**Pull request by AvoMandjian**
Creates an [Expression] checking if the value[List] in the column intersects with the given value[List]

Let's say we have users table with a column allergicToIds where it represents the allergies of a user from allergies table, the method "intersects" queries all the users that have at least one of the allergies given.

```
where: (p0) => p0.allergicToIds.intersects(allergyIds),
```

Note: allergicToIds and allergyIds are both List

## Pre-launch Checklist

- [x] I read the [Contribute](https://docs.serverpod.dev/contribute) page and followed the process outlined there for submitting PRs.
- [x] This update contains only one single feature or bug fix and nothing else. (If you are submitting multiple fixes, please make multiple PRs.)
- [x] I read and followed the [Dart Style Guide](https://dart.dev/guides/language/effective-dart/style) and formatted the code with [dart format](https://dart.dev/tools/dart-format).
- [x] I listed at least one issue that this PR fixes in the description above.
- [x] I updated/added relevant documentation (doc comments with `///`), and made sure that the documentation follows the same style as other Serverpod documentation. I checked spelling and grammar.
- [ ] I added new tests to check the change I am making.
- [ ] All existing and new tests are passing.
- [ ] Any breaking changes are documented below.

### CODE REVIEW

**Comment by AvoMandjian** [comment]
I have read the CLA Document and I hereby sign the CLA

**Review by vlidholt — CHANGES_REQUESTED** [review]
This change will need tests. You can see here how most other tests are written:
https://github.com/serverpod/serverpod/tree/main/tests/serverpod_test_server

Tests need to include different use cases, including using different types, etc.

Also, is it possible to make this with a typed list using templates?

**Comment by vlidholt** [comment]
We're still missing test for this one, but maybe we want to add it to the roadmap? @Isakdl

**Comment by SandPod** [comment]
Closing this since we now provide a similar functionality with the use of `inSet`: https://github.com/serverpod/serverpod/blob/4c557ad45d6682eeb9bcb8210f372134abc21ec1/packages/serverpod/lib/src/database/columns.dart#L180C14-L180C19

**Pull request closed without merging**
