### PR TITLE
Copy fields of ServerException across to DatabaseException

### PR DESCRIPTION
**Pull request by lukehutch**
All of the context of a `PgException` (specifically, the context in its subclass, `ServerException`) is lost when only the message is preserved in a `DatabaseException`. This means that the user cannot be notified, for example, of the character offset of a syntax error, which can make debugging query errors very difficult (you basically have to print out the query on the server console, copy/paste it into a proper Postgres client UI, and see where the error is highlighted).

This change copies all the fields of `ServerException` across to `DatabaseException` in a backwards-compatible way.

I will leave it up to you to add some of this extra info to the error logs, so that Serverpod Insights can report more info on database errors.

## Pre-launch Checklist

- [x] I read the [Contribute](https://docs.serverpod.dev/contribute) page and followed the process outlined there for submitting PRs.
- [x] This update contains only one single feature or bug fix and nothing else. (If you are submitting multiple fixes, please make multiple PRs.)
- [x] I read and followed the [Dart Style Guide](https://dart.dev/guides/language/effective-dart/style) and formatted the code with [dart format](https://dart.dev/tools/dart-format).
- [x] I listed at least one issue that this PR fixes in the description above.
- [x] I updated/added relevant documentation (doc comments with `///`), and made sure that the documentation follows the same style as other Serverpod documentation. I checked spelling and grammar.
- [ ] I added new tests to check the change I am making.
- [ ] All existing and new tests are passing.
- [ ] Any breaking changes are documented below.

### CODE REVIEW

**Comment by SandPod** [comment]
@lukehutch - Would it be OK if I take this PR over and get it in?

**Comment by lukehutch** [comment]
@SandPod please do

**Comment by SandPod** [comment]
Sorry, the close here was not intentional. An incorrect reference to this PR accidentally closed the issue.

**Comment by SandPod** [comment]
This feature was implemented in: https://github.com/serverpod/serverpod/pull/3047

**Pull request closed without merging**
