### PR TITLE
adding client true after serverpod create

### PR DESCRIPTION
**Pull request by abdelaziz-mahdy**
fixing https://github.com/orgs/serverpod/projects/4/views/1?pane=issue&itemId=56584945 by adding the client keys and making them true

Closes: #2013 

## Pre-launch Checklist

- [x] I read the [Contribute](https://docs.serverpod.dev/contribute) page and followed the process outlined there for submitting PRs.
- [x] This update contains only one single feature or bug fix and nothing else. (If you are submitting multiple fixes, please make multiple PRs.)
- [x] I read and followed the [Dart Style Guide](https://dart.dev/guides/language/effective-dart/style) and formatted the code with [dart format](https://dart.dev/tools/dart-format).
- [x] I listed at least one issue that this PR fixes in the description above.
- [x] I updated/added relevant documentation (doc comments with `///`), and made sure that the documentation follows the same style as other Serverpod documentation. I checked spelling and grammar.
- [x] I added new tests to check the change I am making.
- [x] All existing and new tests are passing.
- [x] Any breaking changes are documented below.

If you need help, consider asking for advice on the [discussion board](https://github.com/serverpod/serverpod/discussions).

### CODE REVIEW

**Review by SandPod — CHANGES_REQUESTED** [review]
Awesome work and great tests!

We want to take a bit more of a restrictive approach to the modification of the file to ensure we only update it if it looks as expected.

Please have a look at the comments and let me know if anything is unclear.

**Comment by abdelaziz-mahdy** [comment]
tests on my local machine doesnt get the updated cli for a reason i dont know, 

so i pushed to see the online tests, also i didnt update the test cases will xml need to be removed? and the matching done there too?

**Comment by SandPod** [comment]
Hmm, strange that you could not replicate the tests locally. I ran this locally and it works as expected. Added a couple of minor fixes as a last step.

**Review by SandPod — APPROVED** [review]
Thanks for fixing this! 🙏 

LGTM! 🚀

**Pull request merged**
