### PR TITLE
Upgrade file_picker dep to 8.0.0

### PR DESCRIPTION
**Pull request by lukehutch**
Version 8.0.0 of `file_picker` fixes an important compatibility bug for Android 14+.

## Pre-launch Checklist

- [x] I read the [Contribute](https://docs.serverpod.dev/contribute) page and followed the process outlined there for submitting PRs.
- [x] This update contains only one single feature or bug fix and nothing else. (If you are submitting multiple fixes, please make multiple PRs.)
- [x] I read and followed the [Dart Style Guide](https://dart.dev/guides/language/effective-dart/style) and formatted the code with [dart format](https://dart.dev/tools/dart-format).
- [x] I listed at least one issue that this PR fixes in the description above.
- [x] I updated/added relevant documentation (doc comments with `///`), and made sure that the documentation follows the same style as other Serverpod documentation. I checked spelling and grammar.
- [ ] I added new tests to check the change I am making.
- [x] All existing and new tests are passing.
- [x] Any breaking changes are documented below.

If you need help, consider asking for advice on the [discussion board](https://github.com/serverpod/serverpod/discussions).

## Breaking changes

None, this should be backwards-compatible. This is just a bugfix release.

https://github.com/miguelpruivo/flutter_file_picker/releases

### CODE REVIEW

**Comment by SandPod** [comment]
The tests are failing because the templates have not been updated.

Please apply the same dependency bump in our templates as well:
- `templates/pubspecs/modules/serverpod_auth/serverpod_auth_shared_flutter/pubspec.yaml`
- `templates/pubspecs/modules/serverpod_chat/serverpod_chat_flutter/pubspec.yaml`

**Comment by lukehutch** [comment]
Done!

**Comment by SandPod** [comment]
Seems this bump has a conflict with the our minimum required Dart version.

We allow Dart `3.0.0` as the minimum version. But `file_picker` version `8.0.0` requires `win32` with a minimum version of `5.1.0` which in turn requires Dart with a minimum version of `3.1.0`.

So in order to bump the `file_picker` library we would need to bump our minimum Dart version to 3.1.0.

**Comment by lukehutch** [comment]
OK. Well file_picker doesn't work at all in Android 14+ without the update, because the new security model requires that files have to be requested through the stream API, they can no longer be opened by path. So this may be an important update to make.

**Comment by SandPod** [comment]
Yes, I think it is fine to do this update. Next release from`main` is targeting version 2.0 of Serverpod so it is a good time to bump the Dart SDK version. We just need to make that bump for the entire repo and resolve all dependency issues that arise.

We can take that on and ensure this PR gets into main.

**Pull request closed without merging**
