### PR TITLE
Feature/upsert

### PR DESCRIPTION
**Pull request by sedobrengocce**
Addeda a simple upsert method for a single row and generation code to use upsert method

#232 

## Pre-launch Checklist

- [x ] I read the [Contribute](https://docs.serverpod.dev/contribute) page and followed the process outlined there for submitting PRs.
- [x ] This update contains only one single feature or bug fix and nothing else. (If you are submitting multiple fixes, please make multiple PRs.)
- [x ] I read and followed the [Dart Style Guide](https://dart.dev/guides/language/effective-dart/style) and formatted the code with [dart format](https://dart.dev/tools/dart-format).
- [x ] I listed at least one issue that this PR fixes in the description above.
- [x ] I updated/added relevant documentation (doc comments with `///`), and made sure that the documentation follows the same style as other Serverpod documentation. I checked spelling and grammar.
- [x ] I added new tests to check the change I am making.
- [x ] All existing and new tests are passing.
- [x ] Any breaking changes are documented below.

## Breaking changes
No breakng changes

### CODE REVIEW

**Comment by sedobrengocce** [comment]
I have read the CLA Document and I hereby sign the CLA

**Review by vlidholt — CHANGES_REQUESTED** [review]
Very cool work on this. It's a feature that would be really nice to include in Serverpod.

However, there are some issues that I see with the approach you have taken.

1. The columns are referred to as `String` objects, instead there is generated table class with types for the the columns. These typed columns should be used instead.
2. This works well for the simple case (e.g. one index), but what happens when we have multiple unique indexes defined on a table, it should be as easy to do an upsert with them too. So code generation need to output different objects that exposes the columns for each unique index.
3. There need to be tests for the more complex cases too. E.g. more than one index, multiple indexes, etc.

We may use your PR as a starting point for implementing this feature some time in the future, if you do not have time to address them yourself. :)

**Comment by sedobrengocce** [comment]
> Very cool work on this. It's a feature that would be really nice to include in Serverpod.
> 
> However, there are some issues that I see with the approach you have taken.
> 
> 1. The columns are referred to as `String` objects, instead there is generated table class with types for the the columns. These typed columns should be used instead.
> 2. This works well for the simple case (e.g. one index), but what happens when we have multiple unique indexes defined on a table, it should be as easy to do an upsert with them too. So code generation need to output different objects that exposes the columns for each unique index.
> 3. There need to be tests for the more complex cases too. E.g. more than one index, multiple indexes, etc.
> 
> We may use your PR as a starting point for implementing this feature some time in the future, if you do not have time to address them yourself. :)

I'll continue this feature, maybe i'll become a stable contributor of serverpod :D

**Comment by vlidholt** [comment]
@Isakdl perhaps this can serve as a starting point for this feature?

**Comment by lukehutch** [comment]
I need upsert functionality all the time, and have to resort to a lot of racey boilerplate code to get this to work: query for an existing row, then update if present (first manually copying over the `id` field value from the existing record to the updated version of the record), or insert if not present. There is obviously a race condition between the read and the write, which may be a problem if for example you want to atomically increment a counter in a single query.

What I would like to see in the upsert API is parameters along the lines of those of a `fold` operation: base case, operator, and next operand. The base case contains the values to assume the row's fields have if there is no existing value in the database (the base case for addition is usually the additive identity `0`, for multiplication is usually the multiplicative identidy `1`, and for string concatenation is usually the empty string `""`). The operator takes the existing value, and converts it into the new value, by adding in the operand from the new row that is provided to the API.

The operand can simply set the column value to the value in the new row, if you don't want to base the new value on the old value, but the beauty of doing things this way is from a single API, `upsert` is supported, but so too are atomic counters, or other atomic mutation operations, on multiple columns at once, within a single row. And all of this works with Postgres' "update on conflict" model (Postgres doesn't have true upsert).

The base case record should be created in a lambda, and lazily called, so that the base case record is never constructed if it is not needed. The operators should also be given in lambdas, like current `where` clauses, so that column references are available.

I'm just spitballing here, but this is the sort of API that I am proposing:

```dart
// Given incoming captured vars: `commentSpamScore`, `commenterUserId`
await UserStats.db.upsert(
  // The base case is called `ifNotPresent`
  ifNotPresent: () => UserStats(commentCount: 0, spamScore: 0.0),
  // The operands are called `updates`
  updates: [
    // The operators are called `UpsertOperator`, and they take a column reference
    // (corresponding to their generic type, which can be inferred, and a column
    // update expression).
    // Here `(t)` is the column containing the old value, so either represents the
    // field value from the base case, if no existing record, or the column value
    // from the existing record, if present.
    UpsertOperator<ColumnInt>(UserStats.t.commentCount, (t) => t + 1),
    UpsertOperator<CoulmnDouble>(UserStats.t.spamScore, (t) => t + commentSpamScore),
  ],
  where: (t) => t.userId == commenterUserId,
);
```

If you just want to do a regular upsert, you don't need the `t + ` part in the operator expression. In this case, `ifNotPresent` can be `null` (not provided):

```dart
await UserStats.db.upsert(
  updates: [
    UpsertOperator<ColumnInt>(UserStats.t.commentCount, (t) => 1),
    UpsertOperator<CoulmnDouble>(UserStats.t.spamScore, (t) => commentSpamScore),
  ],
  where: (t) => t.userId == commenterUserId,
);
```

So if the result type of an operator lambda like `(t) => 1` is a value, not an `Expression`, then a regular upsert (implemented by `update on conflict`) is executed.

Also if you want to write a record only if it doesn't already exist in the database, you can do the opposite, but include only `ifNotPresent`, but not `updates`:

```dart
await UserStats.db.upsert(
  ifNotPresent: () => UserStats(commentCount: 1, spamScore: commenSpamScore),
  where: (t) => t.userId == commenterUserId,
);
```

**Comment by SandPod** [comment]
Closing this PR as it is incomplete.

Will add a reference to this PR in the issue tracking the feature and once it is implemented, if this as used as inspiration, @sedobrengocce should be credited as a co-author.

**Pull request closed without merging**
