### PR TITLE
Update signin_button.dart, fixed a couple of comments

### PR DESCRIPTION
**Pull request by Pingear**
## Pre-launch Checklist
- [x] I updated/added relevant documentation (doc comments with `///`), and made sure that the documentation follows the same style as other Serverpod documentation. I checked spelling and **grammar**.

<hr>

**_I have read the CLA Document and I hereby sign the CLA_**

<hr>

### CODE REVIEW

**Comment by Pingear** [comment]
recheck

**Comment by Pingear** [comment]
recheck

**Comment by vlidholt** [comment]
@Pingear I think you will need to post a comment with the text "I have read the CLA Document and I hereby sign the CLA" for the bot to pick it up. Also, make sure you are using the same email for you Github login as you have for the commits.

PR looks good otherwise!

**Comment by Pingear** [comment]
I have read the CLA Document and I hereby sign the CLA

**Review by vlidholt — APPROVED** [review]

**Pull request merged**
