### PR TITLE
Add sign in customizable label & icon

### PR DESCRIPTION
**Pull request by lucasvaudey**
Adding to sign in buttons customizable label & icon.

Issue: #731

## Pre-launch Checklist

- [x] I read the [Contribute](https://docs.serverpod.dev/contribute) page and followed the process outlined there for submitting PRs.
- [x] This update contains only one single feature or bug fix and nothing else. (If you are submitting multiple fixes, please make multiple PRs.)
- [x] I read and followed the [Dart Style Guide](https://dart.dev/guides/language/effective-dart/style) and formatted the code with [dart format](https://dart.dev/tools/dart-format).
- [x] I listed at least one issue that this PR fixes in the description above.
- [x] I updated/added relevant documentation (doc comments with `///`), and made sure that the documentation follows the same style as other Serverpod documentation. I checked spelling and grammar.
- [ ] I added new tests to check the change I am making.
- [x] All existing and new tests are passing.
- [x] Any breaking changes are documented below.

## Breaking changes
None

### CODE REVIEW

**Comment by lucasvaudey** [comment]
I have read the CLA Document and I hereby sign the CLA

**Comment by Isakdl** [comment]
I'm not totally convinced this is a good idea for all the buttons.

For example both Google and Apple have strict guidelines what you are allowed to do with their sign in buttons.
See: [Apple sign in button guide line](https://developer.apple.com/design/human-interface-guidelines/sign-in-with-apple#Creating-a-custom-Sign-in-with-Apple-button)
See: [Google sign in button guide line](https://developers.google.com/identity/branding-guidelines)

The icon is very strict and you are only allowed to use pre-approved logos. For the text you are a little more flexible, but you are still only allowed a short list of approved texts. Now of course the text can also be displayed in different languages.

If you do not follow these guidelines your app may be declined when getting reviewed when publishing to play / app store.


As for the firebase button I think we are fine to add this.

**Comment by lucasvaudey** [comment]
@Isakdl Is that okay for you if I just allow change in the text value for Apple/google buttons ? That way we can translate these ?

**Comment by Isakdl** [comment]
@lucasvaudey I think that makes sense, but perhaps we should add some documentation comments referencing the official button documentation. To guide people in the correct direction and note that they are not allowed to write anything they want in the button label.

**Review by Isakdl — APPROVED** [review]
LGTM 🚀! Thank you

**Pull request merged**
