### PR TITLE
feat: add support snack case for fields

### PR DESCRIPTION
**Pull request by II11II**
_Replace this paragraph with a description of what this PR is changing or adding, and why._

_List which issues are fixed by this PR. You must list at least one issue._

## Pre-launch Checklist

- [X] I read the [Contribute](https://docs.serverpod.dev/contribute) page and followed the process outlined there for submitting PRs.
- [X] This update cointains only one single feature or bug fix and nothing else. (If you are submitting multiple fixes, please make multiple PRs.)
- [X] I read and followed the [Dart Style Guide](https://dart.dev/guides/language/effective-dart/style) and formatted the code with [dart format](https://dart.dev/tools/dart-format).
- [X] I listed at least one issue that this PR fixes in the description above.
- [ ] I updated/added relevant documentation (doc comments with `///`), and made sure that the documentation follows the same style as other Serverpod documentation. I checked spelling and grammar.
- [ ] I added new tests to check the change I am making.
- [X] All existing and new tests are passing.
- [ ] Any breaking changes are documented below.

If you need help, consider asking for advice on the [discussion board](https://github.com/serverpod/serverpod/discussions).

## Breaking changes

_If you have done any breaking changes, make sure to outline them here, so that they can be included in the notes for the next release._

### CODE REVIEW

**Comment by II11II** [comment]
I have read the CLA Document and I hereby sign the CLA

**Comment by II11II** [comment]
#481

**Comment by vlidholt** [comment]
You will need to run `dart format` on your code for it to pass the tests.

**Comment by II11II** [comment]
@vlidholt 
image
I run the command that ci runs, but nothing is changed

**Comment by vlidholt** [comment]
What's run in the CI is only to verify that dart format has been run. As you can see output is set to none.

You should just run `dart format`, don't add any flags.

**Comment by II11II** [comment]
I have read the CLA Document and I hereby sign the CLA

**Comment by vlidholt** [comment]
@II11II Looking good now, thank you! :)

**Pull request merged**
