### PR TITLE
fix: Respond with 400 when throwing serializable exceptions.

### LINKED ISSUE #2940: Respond with HTTP code 400 instead of 500 upon serializable exception
**Describe the bug**
Currently Serverpod responds with HTTP code 500 when an endpoint method throws a serializable exception.

**Expected behavior**
Serverpod should respond with HTTP code 400 instead of 500 when an endpoint method throws a serializable exception.

### PR DESCRIPTION
**Pull request by arpitgupta-it**
## Description
- Closes #2940 

## Pre-launch Checklist

- [x] I read the [Contribute](https://docs.serverpod.dev/contribute) page and followed the process outlined there for submitting PRs.
- [x] This update contains only one single feature or bug fix and nothing else. (If you are submitting multiple fixes, please make multiple PRs.)
- [ ] I read and followed the [Dart Style Guide](https://dart.dev/guides/language/effective-dart/style) and formatted the code with [dart format](https://dart.dev/tools/dart-format).
- [x] I listed at least one issue that this PR fixes in the description above.
- [ ] I updated/added relevant documentation (doc comments with `///`), and made sure that the documentation follows the same style as other Serverpod documentation. I checked spelling and grammar.
- [ ] I added new tests to check the change I am making.
- [x] All existing and new tests are passing.
- [ ] Any breaking changes are documented below.

If you need help, consider asking for advice on the [discussion board](https://github.com/serverpod/serverpod/discussions).

## Breaking changes

_If you have done any breaking changes, make sure to outline them here, so that they can be included in the notes for the next release._

### CODE REVIEW

**Comment by arpitgupta-it** [comment]
I have read the CLA Document and I hereby sign the CLA

**Comment by hampuslavin** [comment]
Hi @arpitgupta-it !
Thanks for submitting this fix 🌟  To make this PR pass you just need to update the failing test to expect a status code 400 instead of 500 (`tests/serverpod_test_server/test_e2e/json_protocol_test.dart`).

**Comment by hampuslavin** [comment]
Hi @arpitgupta-it ! I think you just need to sign the CLA again.

**Comment by arpitgupta-it** [comment]
recheck

**Comment by arpitgupta-it** [comment]
@hampuslavin all done!!

**Review by hampuslavin — APPROVED** [review]
Nice! 🏎️ 🌟

**Pull request merged**
