### PR TITLE
Fix direct upload for custom Cloud storage by FileUploader

### PR DESCRIPTION
**Pull request by pro100andrey**
Server has condition for setting `readBody`  to `false` only for `serverpod_cloud_storage` path:

```dart
// server.dart
else if (uri.path == '/serverpod_cloud_storage') {
      readBody = false;
```

My direct upload description has` /local_cloud_storage` path:

```dart
final uri = Uri(
      scheme: config.apiServer.publicScheme,
      host: config.apiServer.publicHost,
      port: config.apiServer.publicPort,
      path: '/local_cloud_storage',
      queryParameters: <String, dynamic>{
        'method': 'upload',
        'storage': storageId,
        'path': path,
        'key': uploadEntry.authKey,
      },
 );
```

After executing code below:

  ``` dart
final filePath = selectCreatePostImageFilePath(state)!;
final uploadDescription = await getHttpClient()
    .files
    .localCloudStorage
    .getPublicUploadDescription(
    'file',
    '.jpg',
);

final uploader = FileUploader(uploadDescription);
final file = File(filePath);
final length = file.lengthSync();
final stream = file.openRead(0, length);
final uploadResult = await uploader.upload(stream, length);
```

Server throw error:

```logs
2023-05-25 16:58:43.526307Z Internal server error. Failed to read body of request.
FormatException: Invalid UTF-8 byte (at offset 0)
```

because `readBody` is true.

For fix I added condition 'request.headers.contentType?.mimeType == ContentType.binary.mimeType' to check if the Content-Type of the request is binary and set `readBody` to `false`. This solution adds generic binary data request handling for `DatabaseCloudStorage` or custom implementation.

[_List which issues are fixed by this PR. You must list at least one issue._](https://github.com/serverpod/serverpod/issues/941)

## Pre-launch Checklist

- [x] I read the [Contribute](https://docs.serverpod.dev/contribute) page and followed the process outlined there for submitting PRs.
- [x] This update contains only one single feature or bug fix and nothing else. (If you are submitting multiple fixes, please make multiple PRs.)
- [x] I read and followed the [Dart Style Guide](https://dart.dev/guides/language/effective-dart/style) and formatted the code with [dart format](https://dart.dev/tools/dart-format).
- [x] I listed at least one issue that this PR fixes in the description above.
- [x] I updated/added relevant documentation (doc comments with `///`), and made sure that the documentation follows the same style as other Serverpod documentation. I checked spelling and grammar.
- [ ] I added new tests to check the change I am making.
- [x] All existing and new tests are passing.
- [ ] Any breaking changes are documented below.

If you need help, consider asking for advice on the [discussion board](https://github.com/serverpod/serverpod/discussions).

## Breaking changes

No breaking changes

### CODE REVIEW

**Comment by pro100andrey** [comment]
I have read the CLA Document and I hereby sign the CLA
recheck

**Comment by pro100andrey** [comment]
I have read the CLA Document and I hereby sign the CLA

**Comment by pro100andrey** [comment]
recheck

**Comment by pro100andrey** [comment]
recheck

**Comment by vlidholt** [comment]
Why are you not using the `serverpod_cloud_storage` path for your upload? How are you uploading your file? For most use cases, you want to upload the file directly to the upload servers, hence bypassing your Serverpod server.

**Comment by pro100andrey** [comment]
Hi @vlidholt,

I am not using the serverpod_cloud_storage path because retrieving the file through the CloudStoragePublicEndpoint will intercept it. Here is the code snippet:

 ```dart 
const _endpointName = 'serverpod_cloud_storage';

/// Endpoint for the default public [DatabaseCloudStorage].
class CloudStoragePublicEndpoint extends Endpoint {
  @override
  bool get sendByteDataAsRaw => true;

  /// Retrieves a file from the public database cloud storage.
  Future<ByteData?> file(MethodCallSession session, String path) async {
    var response = session.httpRequest.response;

    // Fetch the file from storage.
    var file =
        await session.storage.retrieveFile(storageId: 'public', path: path);
```
This code snippet shows that the file is being fetched from storage using` session.storage.retrieveFile()` with the storage ID set to 'public'. The `CloudStoragePublicEndpoint` will attempt to retrieve the file from the `DatabaseCloudStorage`.

To handle file storage and retrieval from a local server folder instead of using the serverpod_cloud_storage path, i have created a custom implementation called `LocalCloudStorage` that extends `CloudStorage`. I created a custom `LocalStoragePublicEndpoint` class similar to the existing `CloudStoragePublicEndpoint` in order to separate the logic for saving to the database or a custom storage.

Based on these changes, i have created a pull request to incorporate this functionality.

**Comment by vlidholt** [comment]
We'll need a bit more time on this one to, just to be 100% sure it doesn't break anything.

**Comment by lukehutch** [comment]
I was staring at exactly this line today, wondering what on earth the logic for that line could be, as I debugged #981... the proposed fix looks like it was the original intent.

However there's a bigger issue here. The body of the request always has to be decoded. The question is only whether the result should be run through `Utf8Decoder().convert(data)`. Compare:

**`server.dart`**:
```dart
Future<String?> _readBody(HttpRequest request) async {
    // TODO: Find more efficient solution?
    var len = 0;
    var data = <int>[];
    await for (var segment in request) {
      len += segment.length;
      if (len > serverpod.config.maxRequestSize) return null;
      data += segment;
    }
    return const Utf8Decoder().convert(data);
  }
```

**`public_endpoint.dart`** (called for `uri.path == '/serverpod_cloud_storage'`):
```dart
  Future<List<int>?> _readBinaryBody(HttpRequest request) async {
    // TODO: Find more efficient solution?
    var len = 0;
    var data = <int>[];

    await for (var segment in request) {
      len += segment.length;
      if (len > server.serverpod.config.maxRequestSize) return null;
      data += segment;
    }
    return data;
  }
```

This all needs to be refactored so that the body is extracted just once, no matter what endpoint.

Furthermore, this comment: `// TODO: Find more efficient solution` needs to be addressed by using `BytesBuilder`, not `List<int>`!

**Comment by lukehutch** [comment]
I didn't see #952 before, but it looks like we are (almost) totally on the same page, re. my previous comment.

**Pull request closed without merging**
