### PR TITLE
"order by random()", fetch rows randomly

### PR DESCRIPTION
**Pull request by Aksoyhlc**
Random fetching of rows in the table in the database.

_List which issues are fixed by this PR. You must list at least one issue._

## Pre-launch Checklist

- [x] I read the [Contribute](https://docs.serverpod.dev/contribute) page and followed the process outlined there for submitting PRs.
- [x] This update contains only one single feature or bug fix and nothing else. (If you are submitting multiple fixes, please make multiple PRs.)
- [x] I read and followed the [Dart Style Guide](https://dart.dev/guides/language/effective-dart/style) and formatted the code with [dart format](https://dart.dev/tools/dart-format).
- [x] I listed at least one issue that this PR fixes in the description above.
- [x] I updated/added relevant documentation (doc comments with `///`), and made sure that the documentation follows the same style as other Serverpod documentation. I checked spelling and grammar.
- [x] I added new tests to check the change I am making.
- [x] All existing and new tests are passing.
- [x] Any breaking changes are documented below.

If you need help, consider asking for advice on the [discussion board](https://github.com/serverpod/serverpod/discussions).

## Breaking changes

**orderBy** or **orderDescending** cannot be used at the same time as **random**.

### CODE REVIEW

**Comment by Aksoyhlc** [comment]
I have read the CLA Document and I hereby sign the CLA

**Comment by SandPod** [comment]
Hey @Aksoyhlc 👋 

Thank you for your suggested contribution.

I have a couple of questions before we may consider this feature.

1. What is the intended use case for the command and how does it benefit all Serverpod users?
2. Have you considered any other approaches to achieve this use case?
3. What are the performance implications of this command? - As far as I understand, creating a query calling `order by random()` will call the function `random()` for each row in the database, assign the resulting number to the row and then sort the rows based on that. Making a function call for each row in the database seems like a red flag for me performance wise.
4. With this change, the interface of the find method becomes quite convoluated. This would result in 4 separate parameters that influence how the resulting data is ordered. Do you have any suggestions for improvements to make the interface simpler to use?

**Comment by Aksoyhlc** [comment]
Hello @SandPod 

1. This would be useful for those who want to fetch random records from a table. For example, selecting 100 questions out of 20,000 quiz questions belonging to category X.
2. It can be done by retrieving all IDs and then taking 100 random ones among them with an IN query, but I think using the random expression might be more practical.
3. Unfortunately, I haven't tested the performance yet, so I don't know the difference between the "ORDER BY RANDOM" method and the second alternative.
4. findRandom could be an option; other than that, I couldn't think of anything else.

**Comment by SandPod** [comment]
@Aksoyhlc Sorry for the late reply here.

I just want to clarify that I think the feature itself is actually quite neat.

But for us to take this in and continue to support it we would need some data behind the performance implication of the query and a good solution to make the interface cleaner.

**Pull request closed without merging**
