### PR TITLE
feat: Support Order By and Where expressions on many relation for select and count queries.

### PR DESCRIPTION
**Pull request by SandPod**
Closes: https://github.com/serverpod/serverpod/issues/1307
Closes: https://github.com/serverpod/serverpod/issues/1308

### Features
- Support for many relations in Where expressions for Select and Count queries.
- Support for many relations in Order By for Select queries.

#### Examples
Example on Where Expression filtering on many relation. The expression retrieves all customers that have ordered "take away".

``` dart
Customer.find(
      session,
      where: (t) =>
          t.orders((o) => o.description.equals('take away')),
);
```

Example on Where Expression filtering on many relation. The expression retrieves all customers that have ordered "take away" more than 3 times.
``` dart
Customer.find(
      session,
      where: (t) =>
          t.orders((o) => o.description.equals('take away')).count > 3,
);
```

Example on Order By filtering on many relation. The customers are ordered descending by the amount of "take away" orders.

``` dart
Customer.find(
      session,
      orderBy: Customer.t.orders((o) => o.description.equals('take away').count,
      orderDescending: true,
    );
```

###  Adds
Following additions were required to support the new functionality. Some of these should probably have been their own PRs.
#### Columns And Expressions
- New Column type, ColumnCountAggregate, to handle aggregate columns used on many relations.
- New expression type, AggregateExpression, to handle aggregate expressions used on many relations.
- New `ManyRelation` class that provides a `count` getter to perform actions on a many relation field.

#### Code generation
- New expression builder, `<EntityName>WithoutManyRelationsExpressionBuilder`, that does not contain many relations used when filtering a many relation table. This is used because we don't want to perform the nested queries that would be required to perform multiple `counts` in the same request. The recommended way now is to perform multiple request instead.
- New table type `<EntityName>WithoutManyRelationsTable` used in the new expression builder.
- Implicit relation fields are marked with `$`, such as `$_companyEmployeesCompanyId`.

#### Analyzer
- Store field name in ListRelationDefinition
- Store if foreign field is implicit in ListRelationDefintion. This is used to determine if field should be marked with `$` in code generation.

### Guidelines for review
This PR unfortunately does not have the best commit history. The problem became a bit to complicated for me to ensure a good history. I would recommend reviewing it by looking at the complete diff.

The commits are still mostly self contained, except for the last few, with clear motivations for the change.

### Next step
Add support for filtering on many relations in delete query - https://github.com/serverpod/serverpod/issues/1400.
Support for delete query was not included in this PR since it seems like we need to refactor the relationship between expressions and columns to support it. I would rather do that as its own PR.

## Pre-launch Checklist

- [x] I read the [Contribute](https://docs.serverpod.dev/contribute) page and followed the process outlined there for submitting PRs.
- [ ] This update contains only one single feature or bug fix and nothing else. (If you are submitting multiple fixes, please make multiple PRs.)
- [ ] I read and followed the [Dart Style Guide](https://dart.dev/guides/language/effective-dart/style) and formatted the code with [dart format](https://dart.dev/tools/dart-format).
- [ ] I listed at least one issue that this PR fixes in the description above.
- [ ] I updated/added relevant documentation (doc comments with `///`), and made sure that the documentation follows the same style as other Serverpod documentation. I checked spelling and grammar.
- [ ] I added new tests to check the change I am making.
- [ ] All existing and new tests are passing.
- [ ] Any breaking changes are documented below.

If you need help, consider asking for advice on the [discussion board](https://github.com/serverpod/serverpod/discussions).

## Breaking changes

_If you have done any breaking changes, make sure to outline them here, so that they can be included in the notes for the next release._

### CODE REVIEW

**Comment by lukehutch** [comment]
Thanks for pointing me to this PR.

The meaning of the syntax is a bit opaque. I assume nesting syntax like this produces an inner join? Is that what you mean by a "many relation"? One-to-many?

I was struggling to figure out how `t.orders` called as a function, when normally `t.orders` would be a field type. I think the type changes when you add `, relation(...)` to the yaml definition?

Can you please explain the syntax of the following example from your tests? This is not at all clear to me:

```yaml
class: Comment
table: comment
fields:
  description: String
  orderId: int
  order: Order?, relation(name=order_comment, field=orderId)
```

```yaml
class: Order
table: order
fields:
  description: String
  comments: List<Comment>?, relation(name=order_comment)
  customerId: int
  customer: Customer?, relation(name=customer_order, field=customerId)
```

```
class: Customer
table: customer
fields:
  name: String
  orders: List<Order>?, relation(name=customer_order)
```yaml

I think that you have to have a matching `name=` value between two tables, one of which specifies a `field=`, and one of which doesn't? But the specified field is in the class that names the field, so I don't see how this is used for a join, since no corresponding field in the other class is specified...

**Comment by lukehutch** [comment]
Another thing -- for my usecase in #1304, I need to join user-created content rows with a user block action table. When user A queries and gets a a result-set that would normally consist of posts by user B, and user B has blocked user A, then I want to remove the posts by user B from the result set. So what I actually need to do is *negate* the nested query: "Return all posts from table `posts`, except when there's a row in the `blocked` table where `blocked.blocker = B` and `blocked.blockee = A`". Is this possible with your PR?

**Comment by Isakdl** [comment]
@lukehutch For a more clear syntax explanation look at this PR: https://github.com/serverpod/serverpod/pull/1314

the `name` keyword is only needed in case you need to access the object on both sides of the relation. The keyword resolves that the specified `relation` should be connected. 

For the order by / where, on relational objects work a little differently than normal fields. They will indeed become joins in the query to be able to do the filtering.

**Comment by lukehutch** [comment]
@Isakdl Please see my previous comment, we hit send at almost the same exact time...

I looked at #1314, but I am even more confused now. I know this seems straightforward to you, but without the months of context of the work you have been doing on this, nothing about the explanation there makes sense to me. Can you please augment those examples with a demonstration of the exact SQL that is generated from given queries written in Dart, given the YAML definitions? I have no idea what the YAML represents in terms of Dart API or SQL query structure.

**Comment by SandPod** [comment]
Hey! Great questions, we are modeling your case and testing it out. Will get back to you 👍

**Comment by lukehutch** [comment]
> Hey! Great questions, we are modeling your case and testing it out. Will get back to you 👍

Thanks, I edited it slightly to make it more clear.

Basically if someone blocked you, then you should not be able to see anything they post.

The blocked table consists of indexed "blocker" and "blockee" userId fields. Posts also have an "author" userId field.

**Comment by Isakdl** [comment]
Ahh I see the confusion! The yaml syntax does not create any SQL queries to fetch data. It setups the models in dart and it sets up the SQL queries to create the tables and how they are related to each other! 

This PR here adds the ability for you to filter and order the result from queries by related tables in 1:n relations. This is achieved by building joins in the background. 

This is also different from the data that is returned which is managed by the `include` field in the `find` method. (only implemented for 1:1 relations currently). 

Example of 1:1 relation
---
```yaml
# address.yaml
class: Address
table: address
fields:
  street: String
  inhabitantId: int?
  inhabitant: Citizen?, relation(name=citizen_address, field=inhabitantId)
indexes:
  inhabitant_address_idx:
    fields: inhabitantId
    unique: true

# citizen.yaml
class: Citizen
table: citizen
fields:
  name: String
  address: Address?, relation(name=citizen_address)
```
This sets up a relation 1:1 relation between `citizen` and `address`.

The corresponding SQL code will be:

```sql

--
-- Class Address as table address
--
CREATE TABLE "address" (
    "id" serial PRIMARY KEY,
    "street" text NOT NULL,
    "inhabitantId" integer
);

--
-- Class Citizen as table citizen
--
CREATE TABLE "citizen" (
    "id" serial PRIMARY KEY,
    "name" text NOT NULL,
);

-- Indexes
CREATE UNIQUE INDEX "inhabitant_address_idx" ON "address" USING btree ("inhabitantId");

--
-- Foreign relations for "address" table
--
ALTER TABLE ONLY "address"
    ADD CONSTRAINT "address_fk_0"
    FOREIGN KEY("inhabitantId")
    REFERENCES "citizen"("id")
    ON DELETE CASCADE
    ON UPDATE NO ACTION;
```

 
To create a query in dart getting an citizen with an address you write it like so:

```dart
await Citizen.db.find(
  session,
  orderBy: Citizen.t.id,
  include: Citizen.include(
    address: Address.include(),
  ),
);
```

Which in the background generates the following SQL query:


```sql
SELECT
  citizen."id" AS "citizen.id",
  citizen."name" AS "citizen.name",
  citizen_address_address."id" AS "citizen_address_address.id",
  citizen_address_address."street" AS "citizen_address_address.street",
  citizen_address_address."inhabitantId" AS "citizen_address_address.inhabitantId"
FROM
  "citizen"
  LEFT JOIN "address" AS citizen_address_address ON citizen."id" = citizen_address_address."inhabitantId"
ORDER BY
  citizen."id"
```

To fetch citizens based on the address but NOT include the address in the result you can do it like so:

```dart
Citizen.db.find(
  session,
  where: (t) => t.address.street.equals('My street'),
);
```

The generated SQL query for this:

```sql
SELECT
  citizen."id" AS "citizen.id",
  citizen."name" AS "citizen.name",
FROM
  "citizen"
  LEFT JOIN "address" AS citizen_address_address ON citizen."id" = citizen_address_address."inhabitantId"
WHERE
  citizen_address_address."street" = 'My street'
```

## Your problem

Your problem is a self many-to-many relationship, we do actually support the explicit case after this PR. We have yet to start the real work on many-to-many (implicit relations). 

We did run into two problems with your example, so thank you very much this test case has help us a lot!

We found one small issue in our protocol validation not allowing `parent` and `name` at the same time. This is trivial to fix. The second issue is related to this PR in how we manage the where query for lists, we will resolve that before we merge!

To model your problem, you need three protocol files defined like below:

```yaml
# blocked.yaml
class: Blocked
table: blocked
fields:
  blocker: int, relation(name=blocked_by, parent=author)
  blockee: int, relation(name=blocker, parent=author)
indexes:
  blocked_blocker_blockee_idx:
    fields: blocker, blockee
    unique: true

# author.yaml
class: Author
table: author
fields:
  name: String
  blockedBy: List<Blocked>?, relation(name=blocked_by) 
  blocked: List<Blocked>?, relation(name=blocker) 

# post.yaml
class: Post
table: post
fields:
  text: String
  author: Author?, relation
``` 


Then to query for all posts NOT blocked by ME, you can write it like so:

```dart
Future<List<Posts>> findAllNonBlockedPosts(
  Session session, {
  required Author reader,
}) async {
  return await Posts.find(
    session,
    where: (t) => t.author.blockedBy((b) => b.blockee.notEquals(reader.id)),
  );
}
```

This will generate the following query in the background:

```sql
SELECT posts."id" AS "posts.id",
    posts."text" AS "posts.text",
    posts."authorId" AS "posts.authorId"
FROM "posts"
    LEFT JOIN "author" AS posts_author_author ON posts."authorId" = posts_author_author."id"
    LEFT JOIN "blocked" AS posts_author_author_blockedBy_blocked ON posts_author_author."id" = posts_author_author_blockedBy_blocked."blockerId"
WHERE (
        posts_author_author_blockedBy_blocked."blockeeId" != 61
        OR posts_author_author_blockedBy_blocked."blockeeId" IS NULL
    )
GROUP BY "posts.id",
    "posts.text",
    "posts.authorId"
```

Hope this helps, let me know if I need to clarify anything.

**Comment by SandPod** [comment]
After further investigation this solution does not meet the requirements of this feature.

Main issue identified at the moment are specifically exclusive queries. Filtering on requirements that would not be true for all joins to the many relation table.

Closing the PR to continue the work.

**Comment by SandPod** [comment]
@lukehutch - The reply above would not yield the correct result in your case and was a great example of the issues with the current solution.

**Pull request closed without merging**
