### PR TITLE
Added authentication by phone number via SMS

### PR DESCRIPTION
**Pull request by mdrobotov**
This PR adds the ability to authenticate by phone number by sending SMS, similar to email authentication.

Added the ability to authenticate by phone number via SMS to the ``serverpod_auth`` module, also added the flutter code.

## Pre-launch Checklist

- [x] I read the [Contribute](https://docs.serverpod.dev/contribute) page and followed the process outlined there for submitting PRs.
- [x] This update contains only one single feature or bug fix and nothing else. (If you are submitting multiple fixes, please make multiple PRs.)
- [x] I read and followed the [Dart Style Guide](https://dart.dev/guides/language/effective-dart/style) and formatted the code with [dart format](https://dart.dev/tools/dart-format).
- [x] I listed at least one issue that this PR fixes in the description above.
- [x] I updated/added relevant documentation (doc comments with `///`), and made sure that the documentation follows the same style as other Serverpod documentation. I checked spelling and grammar.
- [x] I added new tests to check the change I am making.
- [x] All existing and new tests are passing.
- [x] Any breaking changes are documented below.

If you need help, consider asking for advice on the [discussion board](https://github.com/serverpod/serverpod/discussions).

## Breaking changes

_If you have done any breaking changes, make sure to outline them here, so that they can be included in the notes for the next release._

### CODE REVIEW

**Comment by mdrobotov** [comment]
I have read the CLA Document and I hereby sign the CLA

**Comment by SandPod** [comment]
Hey @mdrobotov!

It is awesome that you have taken a stab on implementing sms auth!

Before we will review this please confirm that:
- You have read the other SMS auth PR and ensured that none of the review comments there apply to this PR: https://github.com/serverpod/serverpod/pull/1362
- You have no merge conflicts with main.

**Comment by mdrobotov** [comment]
@SandPod, please check, I have made the required changes.

**Comment by mdrobotov** [comment]
@hampuslavin, thanks for the feedback!

In the project where I use serverpod, I need authentication by phone number with account confirmation, similar to email authentication, with the possibility of further authorization of the user by number and password. So I implemented it like email authentication. I am ready to implement OTP authorization, but I want to be able to log in with a password, similar to email.

**Comment by hampuslavin** [comment]
>  I need authentication by phone number with account confirmation, similar to email authentication, with the possibility of further authorization of the user by number and password.

Just to understand your use case. You want the user to:
- Sign up with phone number + password, and then verify the phone number with an OTP
- Each time the user signs in after that, they should simply use their user identifier (phone number) + password

Is this correct?

**Comment by mdrobotov** [comment]
@hampuslavin, yes, that's right

**Comment by hampuslavin** [comment]
@mdrobotov Ok, I see! 👍 Your implementation of this will then have to live inside your project (or your own module) instead of inside the Serverpod auth module. The reason is that the broader need that we're currently seeing is password-less login with OTP via SMS, and we want to ensure we can support this mainstream use case first and foremost.

Would you like to help us with this and make the changes as per my [initial comment](https://github.com/serverpod/serverpod/pull/2896#issuecomment-2449674591)? 🚀

**Comment by mdrobotov** [comment]
@hampuslavin, it's clear, well, I can redo the authentication so that authorization takes place without a password using OTP

**Comment by hampuslavin** [comment]
> @hampuslavin, it's clear, well, I can redo the authentication so that authorization takes place without a password using OTP

Awesome! 🚀  Again, just ping here if you have any questions on [the initial points above](https://github.com/serverpod/serverpod/pull/2896#issuecomment-2449674591) 👍

**Pull request closed without merging**
