### PR TITLE
Added http request extension readString/readBytes methods

### PR DESCRIPTION
**Pull request by pro100andrey**
Added http request extension readString/readBytes + fix reset_db.pgsql path for setup-tables (test)

## Pre-launch Checklist

- [x] I read the [Contribute](https://docs.serverpod.dev/contribute) page and followed the process outlined there for submitting PRs.
- [x] This update contains only one single feature or bug fix and nothing else. (If you are submitting multiple fixes, please make multiple PRs.)
- [x] I read and followed the [Dart Style Guide](https://dart.dev/guides/language/effective-dart/style) and formatted the code with [dart format](https://dart.dev/tools/dart-format).
- [x] I listed at least one issue that this PR fixes in the description above.
- [x] I updated/added relevant documentation (doc comments with `///`), and made sure that the documentation follows the same style as other Serverpod documentation. I checked spelling and grammar.
- [ ] I added new tests to check the change I am making.
- [x] All existing and new tests are passing.
- [ ] Any breaking changes are documented below.

If you need help, consider asking for advice on the [discussion board](https://github.com/serverpod/serverpod/discussions).

## Breaking changes
No breaking changes

### CODE REVIEW

**Comment by pro100andrey** [comment]
I have read the CLA Document and I hereby sign the CLA

**Comment by pro100andrey** [comment]
recheck

**Comment by pro100andrey** [comment]
recheck

**Comment by vlidholt** [comment]
Thanks for the contributions! :)

Can you describe in more detail why you want to make this change and what the benefits would be?

**Comment by pro100andrey** [comment]
@vlidholt, This is just a small improvement.

/```dart
// Reads the body of an HTTP request and returns it as a String.
  /// If the request's content length exceeds the [maxSize], an exception
  /// is thrown.
  Future<String> readString({required int maxSize}) async {
    if (contentLength != -1) {
      if (contentLength > maxSize) {
        throw MaximumSizeExceeded(maxSize);
      }

      return utf8.decodeStream(this);
    }

    var data = <int>[];
    await for (var chunk in this) {
      if (data.length + chunk.length > maxSize) {
        throw MaximumSizeExceeded(maxSize);
      }

      data.addAll(chunk);
    }

    return utf8.decode(data);
  }

  /// Reads the body of an HTTP request and returns it as a Uint8List.
  /// If the request's content length exceeds the [maxSize], an exception
  /// is thrown.
  Future<Uint8List> readBytes({required int maxSize}) async {
    if (contentLength != -1 && contentLength > maxSize) {
      throw MaximumSizeExceeded(maxSize);
    }

    var result = BytesBuilder();
    await for (var chunk in this) {
      if (result.length + chunk.length > maxSize) {
        throw MaximumSizeExceeded(maxSize);
      }

      result.add(chunk);
    }

    return result.toBytes();
  }
```

The condition `contentLength != -1 `returns true in most cases, which allows us to immediately check `if contentLength > maxSize` and call `request.close()`. This improves the server's response time by avoiding unnecessary computations of contentLength.

**Comment by pro100andrey** [comment]
@vlidholt ,  As I know the `BytesBuilder/StringBuffer` class provides an efficient way to create and concatenate byte sequences in Dart. Here are a few reasons why `BytesBuilder`  might be better than using lists for working with bytes:

- Memory Efficiency: When using lists, each element in the list is an object that contains additional information such as a reference to the next element, an index, etc. This can lead to inefficient memory usage when storing a large number of bytes. BytesBuilder, on the other hand, uses a contiguous buffer to store the bytes, allowing for more efficient memory utilization.

- Performance Efficiency: When concatenating byte lists, it requires creating new lists and copying data each time, which can take more time and consume more CPU resources. BytesBuilder provides optimized methods for byte concatenation, which can lead to improved performance.

If you have a different perspective, please let me know. I'm open to considering and discussing alternative approaches or the advantages of using lists for working with bytes

**Pull request closed without merging**
