### PR TITLE
Add a convenience method to simplify the access to the cache

### PR DESCRIPTION
**Pull request by wilsonsilva**
This PR adds a convenience method called `Cache#fetch` to simplify the access to the cache, [similar to what Ruby on Rails does](https://api.rubyonrails.org/classes/ActiveSupport/Cache/Store.html#method-i-fetch).

Fetches data from the cache using the given key. If there is data in the cache with the given key, then that data is returned.

If there is no such data in the cache (a cache miss), then `null` will be returned. However, the passed function is executed in
the event of a cache miss. The function's return value will be written to the cache under the given cache key, and that
return value will be returned.

```javascript
// cache hit
cache.write('today', 'Monday');

cache.fetch('today', () async {
  return 'Tuesday';
}); // 'Monday'


// cache miss
cache.get('city'); // null

cache.fetch('city', () async {
  return 'Phuket';
}); // 'Phuket'

cache.get('city'); // 'Phuket'
```

Apologies in advance if this code is substandard. I'm a beginner in Dart and mocktail. And I haven't tried Serverpod yet - I found it a [few hours ago on Twitter](https://twitter.com/FlutterDev/status/1650910696966701075) and noticed that the introductory tutorials used get/set so here I am.

## Challenges
- I had more tests to add to `redis_test.dart`. But I couldn't find a way to generate the `serverpod_test_client/protocol/client` with `utils/generate_all` or `serverpod generate`:

```
00:00 +0 -1: loading test/redis_test.dart [E]
  Failed to load "test/redis_test.dart":
  test/redis_test.dart:82:42: Error: The method 'fetch' isn't defined for the class '_EndpointRedis'.
   - '_EndpointRedis' is from 'package:serverpod_test_client/src/protocol/client.dart' ('../serverpod_test_client/lib/src/protocol/client.dart').
  Try correcting the name to the name of an existing method, or defining a method named 'fetch'.
        var retrieved = await client.redis.fetch<SimpleData>(
                                           ^^^^^
  test/redis_test.dart:92:42: Error: The method 'fetch' isn't defined for the class '_EndpointRedis'.
   - '_EndpointRedis' is from 'package:serverpod_test_client/src/protocol/client.dart' ('../serverpod_test_client/lib/src/protocol/client.dart').
  Try correcting the name to the name of an existing method, or defining a method named 'fetch'.
        var retrieved = await client.redis.fetch<SimpleData>(
                                           ^^^^^
```

- I also tried to avoid mocking the `RedisController`, and wanted to mock `RedisConnection` directly, but the variable `_command` is private. Not a trivial change without Dependency Injection.

- [contribute#editing-the-pubspecyaml-files](https://docs.serverpod.dev/contribute#editing-the-pubspecyaml-files) states that we shouldn't update the pubspec files directly. Initially, I updated the templates and ran the generation scripts, but my IDE complained that the package could not be found.

## Pre-launch Checklist

- [x] I read the [Contribute](https://docs.serverpod.dev/contribute) page and followed the process outlined there for submitting PRs.
- [x] This update contains only one single feature or bug fix and nothing else. (If you are submitting multiple fixes, please make multiple PRs.)
- [x] I read and followed the [Dart Style Guide](https://dart.dev/guides/language/effective-dart/style) and formatted the code with [dart format](https://dart.dev/tools/dart-format).
- [ ] I listed at least one issue that this PR fixes in the description above.
- [x] I updated/added relevant documentation (doc comments with `///`), and made sure that the documentation follows the same style as other Serverpod documentation. I checked spelling and grammar.
- [x] I added new tests to check the change I am making.
- [x] All existing and new tests are passing.
- [x] Any breaking changes are documented below.

### CODE REVIEW

**Comment by wilsonsilva** [comment]
I have read the CLA Document and I hereby sign the CLA

**Comment by wilsonsilva** [comment]
recheck

**Review by vlidholt — CHANGES_REQUESTED** [review]
This is pretty sweet. However, we cannot accept it with tests failing.

Rather than using mocktail, it may be better to write it like an end-to-end test like most of the other tests (for the Redis test).

Best if you can do the update, it may otherwise take us a while to get to it.

**Comment by SandPod** [comment]
@wilsonsilva This is a really neat addition. I will finish it for you and get it into Serverpod.

**Comment by SandPod** [comment]
Consolidated the interface into a single one with an optional parameter for handling the cache miss logic.

Bonus: Apart from adding tests for the cache miss functionality the relevant cache tests from the local cache where ported to the Redis cache.

**Review by vlidholt — APPROVED** [review]
LGTM :)

**Pull request merged**
