### PR TITLE
Feat: Support for "HTML+Dart" application/website

### PR DESCRIPTION
**Pull request by yahu1031**
## Support
Support for web applications/sites `(No Flutter, pure dart)`.

Ref issue: #329 

## Pre-launch Checklist

- [x] I read the [Contribute](https://docs.serverpod.dev/contribute) page and followed the process outlined there for submitting PRs.
- [x] This update contains only one single feature or bug fix and nothing else. (If you are submitting multiple fixes, please make multiple PRs.)
- [x] I read and followed the [Dart Style Guide](https://dart.dev/guides/language/effective-dart/style) and formatted the code with [dart format](https://dart.dev/tools/dart-format).
- [x] I listed at least one issue that this PR fixes in the description above.
- [x] I updated/added relevant documentation (doc comments with `///`), and made sure that the documentation follows the same style as other Serverpod documentation. I checked spelling and grammar.
- [ ] I added new tests to check the change I am making.
- [x] All existing and new tests are passing.
- [x] Any breaking changes are documented below.

## Breaking changes

- **`SecurityContext`**'s variable name has been named from ~~`context`~~ -> `securityContext`
- assertion has been updated accordingly.
- **`SecurityContext`** has been changed to dynamic such that it will allow the website development(No Flutter).

### CODE REVIEW

**Comment by SandPod** [comment]
Hey @yahu1031 👋 

This PR shows more in the diff than what is suspect is connected to the changes your are introducing (thinking about the auth changes for firebase that was recently introduced).

I think this is resolved if the PR is rebased on latest main.

Could you please rebase it?

**Comment by SandPod** [comment]
Hey @yahu1031! 👋 

There seems to be some issue with the diff off this PR, it includes changes that are already on main. Could you please rebase the PR or merge in latest main to see if we can get a clean diff for it?

Then we can review it, as long as all the tests are green :)

**Comment by yahu1031** [comment]
@SandPod Can you check this once now, I merged the main branch.

**Comment by yahu1031** [comment]
e2es are failing for some reason, it will work after sometime not sure why!! Help me fixing it please

**Comment by SandPod** [comment]
Test failures have nothing to do with the changes in this branch.

- One failure is because the test runner on GitHub is slow on MacOS -> we need to increase the test timeout there.
- The other test failure is because the stdout stream is closed when the process is still running -> I will look into this.

Will take a look at you specific changes now.

**Review by SandPod — APPROVED** [review]
Good catch! 👍

**Pull request merged**
